import "@/shared/style/base.scss";

import Head from "./head";
import Pwa from "./pwa";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head />

      <body>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
